import { ConfettiProvider } from '@/components/providers/confetti-provider'
import { ToastProvider } from '@/components/providers/toaster-provider'
import { cn } from '@/lib/utils'
import { ClerkProvider } from '@clerk/nextjs'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ReactNode } from 'react'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<ClerkProvider>
			<html lang="pt-BR">
				<body className={cn('antialiased', inter.className)}>
					<ConfettiProvider />
					<ToastProvider />
					{children}
				</body>
			</html>
		</ClerkProvider>
	)
}
